// Sage Knowledge Base - search index
// Each entry: title (what you're looking for), page + anchor (where it lives),
// pageTitle (shown as context), keywords (extra search terms), snippet (preview text).
var SEARCH_INDEX = [
  // 01 - Espresso Fundamentals
  { title: "The 4 Keys", page: "01-espresso-fundamentals.html", anchor: "four-keys", pageTitle: "Espresso Fundamentals", keywords: "dose pressure temperature steam 18-22g 9 bar 93 130", snippet: "Ideal Dose 18–22g, Optimal Pressure 9 bar, Precise Temperature 93°C, Powerful Steam 130°C." },
  { title: "Reading a Shot", page: "01-espresso-fundamentals.html", anchor: "reading-a-shot", pageTitle: "Espresso Fundamentals", keywords: "under extracted over extracted balanced crema sour bitter diagnosis", snippet: "Diagnose a shot by flow speed, taste, and crema colour - grind finer or coarser." },
  { title: "Under vs. Over-Extraction: Full Terms Glossary", page: "01-espresso-fundamentals.html", anchor: "extraction-glossary", pageTitle: "Espresso Fundamentals", keywords: "under-extracted over-extracted crema pre-infusion tamp dose grind stale beans customer recommendation flowchart", snippet: "Every extraction term: definition, cause, technical fix, and how to explain it to the customer." },
  { title: "Shot Volume Targets", page: "01-espresso-fundamentals.html", anchor: "shot-volume-targets", pageTitle: "Espresso Fundamentals", keywords: "single double shot ml seconds volume", snippet: "Single and double shot ml/time targets for under, balanced, and over extraction." },
  { title: "Pressure / Temperature Flavour Map", page: "01-espresso-fundamentals.html", anchor: "flavour-map", pageTitle: "Espresso Fundamentals", keywords: "grassy sour ashy bitter flavour pressure temperature", snippet: "What each variable being wrong tastes like - a 1°C swing can shift balanced to ashy/bitter." },
  { title: "Dose, Grind & Brew Ratios", page: "01-espresso-fundamentals.html", anchor: "dose-grind", pageTitle: "Espresso Fundamentals", keywords: "ristretto lungo double espresso ratio grams burr", snippet: "Brew ratio table for ristretto, espresso, double espresso, lungo, drip coffee." },
  { title: "Perfect Single-Shot Checklist", page: "01-espresso-fundamentals.html", anchor: "perfect-shot", pageTitle: "Espresso Fundamentals", keywords: "tamp cup fill water filter checklist", snippet: "Pressure, dose, tamp, cup fill, time, and water filter targets for a perfect shot." },
  { title: "Milk Types Reference", page: "01-espresso-fundamentals.html", anchor: "milk-types", pageTitle: "Espresso Fundamentals", keywords: "soy almond oat lactose-free skim whole milk", snippet: "Reference list of milk types agents should recognise." },

  // 02 - Machine Components
  { title: "Core Parts (all machines)", page: "02-machine-components.html", anchor: "core-parts", pageTitle: "Machine Components", keywords: "water pump heating element solenoid hoses circuit board", snippet: "Water pump, heating element, solenoid valve, hoses, circuit boards." },
  { title: "Front Panel / Controls", page: "02-machine-components.html", anchor: "front-panel", pageTitle: "Machine Components", keywords: "hopper grinder dial power tamper portafilter", snippet: "Barista-line front panel control names." },
  { title: "Accessories", page: "02-machine-components.html", anchor: "accessories", pageTitle: "Machine Components", keywords: "milk jug razor cleaning disc water filter holder", snippet: "Full accessory list - portafilter, jug, baskets, Razor™, cleaning tools." },
  { title: "Tamper", page: "02-machine-components.html", anchor: "tamper", pageTitle: "Machine Components", keywords: "group handle 58mm 54mm", snippet: "Packs ground coffee evenly. Sizes 58mm and 54mm." },
  { title: "Filter Baskets - Single Wall vs Dual Wall", page: "02-machine-components.html", anchor: "filter-baskets", pageTitle: "Machine Components", keywords: "pressurized single wall dual wall basket pre-ground 30 day roast when to recommend", snippet: "Single Wall for fresh whole beans under 30 days; Dual Wall for pre-ground or older beans - when to recommend each." },
  { title: "Pressure Gauge", page: "02-machine-components.html", anchor: "pressure-gauge", pageTitle: "Machine Components", keywords: "9 bar resistance puck", snippet: "Measures resistance of water through the puck - should read 9 bar." },
  { title: "Three-Way Solenoid Valve", page: "02-machine-components.html", anchor: "solenoid-valve", pageTitle: "Machine Components", keywords: "dry puck vacuum pump SES500 SES810 Bambino Duo Temp Pro", snippet: "Every machine has one except Bambino (SES500) and Duo Temp Pro (SES810)." },
  { title: "Shower Screen", page: "02-machine-components.html", anchor: "shower-screen", pageTitle: "Machine Components", keywords: "inner shower screen diffuse water group head", snippet: "Diffuses group-head water evenly for consistent strength." },
  { title: "Group Head Seal", page: "02-machine-components.html", anchor: "group-seal", pageTitle: "Machine Components", keywords: "brew head seal silicone ring leaking portafilter lifespan", snippet: "Silicone ring, 1–2 year lifespan; wear shows as leaking around the portafilter." },
  { title: "Feature Legend - ThermoJet, PID, Impress, Auto MilQ", page: "02-machine-components.html", anchor: "feature-legend", pageTitle: "Machine Components", keywords: "thermocoil thermojet pid dual boiler impress puck system auto milq razor water filter reminder", snippet: "Proprietary term glossary: ThermoJet, PID, dual boiler, Impress Puck System, Auto MilQ, Razor." },

  // 03 - Model Specs
  { title: "Model Comparison Table", page: "03-model-specs.html", anchor: "comparison-table", pageTitle: "Model Specifications", keywords: "all 11 models power water tank bean hopper portafilter group head boiler grinder display", snippet: "Full spec comparison across all 11 Sage/Breville models." },
  { title: "SES500 Bambino Plus", page: "03-model-specs.html", anchor: "ses500", pageTitle: "Model Specifications", keywords: "bambino plus 1.9L no grinder", snippet: "Compact automatic espresso machine, no built-in grinder." },
  { title: "SES870 Barista Express Safety Guide", page: "03-model-specs.html", anchor: "ses870", pageTitle: "Model Specifications", keywords: "barista express safety guide pictorial", snippet: "Same physical machine as SES875 - pictorial safety guide only." },
  { title: "SES875 Barista Express", page: "03-model-specs.html", anchor: "ses875", pageTitle: "Model Specifications", keywords: "barista express 15 bar adjustable dial", snippet: "Adjustable grind dial, hands-free grinding cradle, Temp Control jug." },
  { title: "SES876 Barista Express Impress", page: "03-model-specs.html", anchor: "ses876", pageTitle: "Model Specifications", keywords: "impress puck system 25 settings less mess", snippet: "The Impress Puck System - intelligent dosing, assisted tamping." },
  { title: "SES878 Barista Pro", page: "03-model-specs.html", anchor: "ses878", pageTitle: "Model Specifications", keywords: "thermojet 30 settings dry puck", snippet: "ThermoJet Heating System, 30 grind settings, Dry Puck Feature." },
  { title: "SES880 Barista Touch", page: "03-model-specs.html", anchor: "ses880", pageTitle: "Model Specifications", keywords: "touch screen preset drinks americano cafe crema", snippet: "Full-colour touch screen with swipe drink menu and preset drinks." },
  { title: "SES882 Barista Touch Impress", page: "03-model-specs.html", anchor: "ses882", pageTitle: "Model Specifications", keywords: "340g hopper 40mm burr assisted tamping barista twist", snippet: "Touch screen guidance, Assisted Tamping, milk-type presets." },
  { title: "SES920 Dual Boiler", page: "03-model-specs.html", anchor: "ses920", pageTitle: "Model Specifications", keywords: "dual boiler 58mm 2.5L press and hold bypass", snippet: "Dual boiler, 9 bar, drop-down swivel foot, Advanced Menu." },
  { title: "SES980 Oracle", page: "03-model-specs.html", anchor: "ses980", pageTitle: "Model Specifications", keywords: "oracle 45 settings long black auto grind dose tamp", snippet: "45 grind settings, Auto Grind/Dose/Tamp, dual-valve descale." },
  { title: "SES985 Oracle Jet", page: "03-model-specs.html", anchor: "ses985", pageTitle: "Model Specifications", keywords: "oracle jet auto milq wifi bluetooth barista guidance cold brew tamper fan", snippet: "ThermoJet, Auto MilQ, Barista Guidance, Wi-Fi/Bluetooth, tamper fan policy." },
  { title: "SES990 Oracle Touch", page: "03-model-specs.html", anchor: "ses990", pageTitle: "Model Specifications", keywords: "oracle touch dual boiler americano cafe crema", snippet: "Touch screen menu, Auto Grind/Dose/Tamp, Americano and Café Crema functions." },

  // 04 - Troubleshooting
  { title: "Start Here: What's the Symptom?", page: "04-troubleshooting.html", anchor: "symptom-router", pageTitle: "Troubleshooting", keywords: "symptom router flowchart triage category water steam grinder power", snippet: "Flowchart: pick the symptom category first, then jump to the right section." },
  { title: "Common Issues Across All Models", page: "04-troubleshooting.html", anchor: "common-issues", pageTitle: "Troubleshooting", keywords: "no water no steam no crema leaking thermal cutout general care", snippet: "The patterns that repeat across nearly every machine - check here first." },
  { title: "Oracle Jet Tamper Fan Policy", page: "04-troubleshooting.html", anchor: "oracle-jet-tamper-fan", pageTitle: "Troubleshooting", keywords: "SES985 tamper fan do not change factory setting 21-23g overdose escalation", snippet: "Never advise changing tamper fan settings. 21–23g overdose = suspected factory defect." },
  { title: "Latch Stuck (SES985 Oracle-family)", page: "04-troubleshooting.html", anchor: "latch-stuck", pageTitle: "Troubleshooting", keywords: "water in latch scale descaler paste do not force", snippet: "Descaler paste on the edge, wait - never force the latch open." },
  { title: "Dual Boiler turns on by itself", page: "04-troubleshooting.html", anchor: "dual-boiler-self-power", pageTitle: "Troubleshooting", keywords: "SES920 self powers on random app notification factory reset", snippet: "5-step process: note SW version, power-cycle, update, factory reset, offer replacement." },
  { title: "Dual Boiler inconsistent auto dial-in shot", page: "04-troubleshooting.html", anchor: "dual-boiler-inconsistent-shot", pageTitle: "Troubleshooting", keywords: "SES920 volume based time based double tap purge tamper fan", snippet: "Check beans, switch dial-in mode, double-tap purge, check tamper fan." },
  { title: "SES500 Bambino Plus troubleshooting", page: "04-troubleshooting.html", anchor: "ses500", pageTitle: "Troubleshooting", keywords: "bambino plus alert lights extraction diagnosis maintenance", snippet: "Full fault table, alert lights, and maintenance schedule for the Bambino Plus." },
  { title: "SES870 Barista Express Safety Guide troubleshooting", page: "04-troubleshooting.html", anchor: "ses870", pageTitle: "Troubleshooting", keywords: "safety guide clean me light no fault table", snippet: "Pictorial safety guide only - no fault table or error codes." },
  { title: "SES875 Barista Express troubleshooting", page: "04-troubleshooting.html", anchor: "ses875", pageTitle: "Troubleshooting", keywords: "filter size leds pressure gauge grinder noise 0808 178 1650", snippet: "Full fault table including grinder issues and support phone number." },
  { title: "SES876 Barista Express Impress troubleshooting", page: "04-troubleshooting.html", anchor: "ses876", pageTitle: "Troubleshooting", keywords: "auto dose severe overdose underdose puck tamp light", snippet: "Dose correction, puck quality, and tamp lever fault table." },
  { title: "SES878 Barista Pro troubleshooting", page: "04-troubleshooting.html", anchor: "ses878", pageTitle: "Troubleshooting", keywords: "error mode icon flush descale menu", snippet: "Error Mode icon → contact Sage Customer Service directly." },
  { title: "SES880 Barista Touch troubleshooting", page: "04-troubleshooting.html", anchor: "ses880", pageTitle: "Troubleshooting", keywords: "factory reset purging error silicone seal 8 step", snippet: "Includes factory reset for purging errors and 8-step seal replacement." },
  { title: "SES882 Barista Touch Impress troubleshooting", page: "04-troubleshooting.html", anchor: "ses882", pageTitle: "Troubleshooting", keywords: "a bit more dosing correction under extracted over extracted", snippet: "Impress Puck System dosing correction and extraction diagnosis." },
  { title: "SES920 Dual Boiler troubleshooting", page: "04-troubleshooting.html", anchor: "ses920", pageTitle: "Troubleshooting", keywords: "E1 E2 E3 error rEST dESC descale pressure gauge 9 bar", snippet: "E1/E2/E3 non-resettable errors; full descale procedure." },
  { title: "SES980 Oracle troubleshooting", page: "04-troubleshooting.html", anchor: "ses980", pageTitle: "Troubleshooting", keywords: "ERR LCD alerts fill tank clean me lock hopper overheat", snippet: "LCD alert glossary and full fault table." },
  { title: "SES985 Oracle Jet troubleshooting", page: "04-troubleshooting.html", anchor: "ses985", pageTitle: "Troubleshooting", keywords: "wifi bluetooth diffuser plate steam ring burr misaligned", snippet: "Includes Wi-Fi setup issues and burr realignment procedure." },
  { title: "SES990 Oracle Touch troubleshooting", page: "04-troubleshooting.html", anchor: "ses990", pageTitle: "Troubleshooting", keywords: "operation error touch screen conical burrs 15 step", snippet: "Operation Error alert and 15-step burr cleaning." },

  // 05 - ANCHOR
  { title: "7 Customer Care Principles", page: "05-customer-care-voice.html", anchor: "principles", pageTitle: "Customer Care Voice", keywords: "bring quality understand judgement honest own match customer", snippet: "The 7 principles behind every Sage support conversation." },
  { title: "Heard, Guided, Confident Framework", page: "05-customer-care-voice.html", anchor: "framework", pageTitle: "Customer Care Voice", keywords: "four pillars empathy compassion professional", snippet: "Three feelings we aim for; Four Pillars of tone." },
  { title: "The ANCHOR Model", page: "05-customer-care-voice.html", anchor: "anchor", pageTitle: "Customer Care Voice", keywords: "acknowledge navigate commit honour own reassure merge what is anchor", snippet: "What ANCHOR is and what each of the 6 letters stands for, with example lines." },
  { title: "What Each Letter Stands For", page: "05-customer-care-voice.html", anchor: "anchor-letters", pageTitle: "Customer Care Voice", keywords: "acknowledge navigate commit honour own reassure letter meaning visual", snippet: "Visual breakdown: A-N-C-H-O-R, one behaviour per letter, in order." },
  { title: "Call Flow Scripts", page: "05-customer-care-voice.html", anchor: "call-flow", pageTitle: "Customer Care Voice", keywords: "start well set the path understand the goal close with clarity", snippet: "Opening lines and structure for every call." },
  { title: "Our Tone", page: "05-customer-care-voice.html", anchor: "tone", pageTitle: "Customer Care Voice", keywords: "warm steady scripted robotic sound like", snippet: "What we sound like vs. what we do not sound like." },
  { title: "Situation Examples", page: "05-customer-care-voice.html", anchor: "situations", pageTitle: "Customer Care Voice", keywords: "premium product out of guarantee repeat fault resists troubleshooting", snippet: "Scripted lines for common call situations." },
  { title: "Handling Angry Customers", page: "05-customer-care-voice.html", anchor: "angry", pageTitle: "Customer Care Voice", keywords: "raised voice manager negative review abusive language policy", snippet: "Key principles and scripted responses for de-escalation." },
  { title: "What Not to Say / What to Say Instead", page: "05-customer-care-voice.html", anchor: "avoid-say", pageTitle: "Customer Care Voice", keywords: "nothing I can do policy I don't know you'll have to wait", snippet: "Banned phrases and their ANCHOR-approved replacements." },
  { title: "General Tips & Formula", page: "05-customer-care-voice.html", anchor: "tips", pageTitle: "Customer Care Voice", keywords: "empathy expertise ownership formula score card", snippet: "Empathy + Expertise + Ownership. Activity score card categories." },
  { title: "Worked Example - Barista Express shuts off mid-brew", page: "05-customer-care-voice.html", anchor: "worked-example", pageTitle: "Customer Care Voice", keywords: "shutting off flickering lights example anchor", snippet: "Full ANCHOR walk-through for a mid-brew shutdown complaint." },
  { title: "Our Brands - Sage, Baratza, Beanz", page: "05-customer-care-voice.html", anchor: "brands", pageTitle: "Customer Care Voice", keywords: "sage baratza beanz brand voice expectations", snippet: "What each brand's customers expect and how to adjust tone." },

  // 06 - Sample Call
  { title: "Sample Call Transcript - Oracle Jet overdose", page: "06-sample-call.html", anchor: "transcript", pageTitle: "Sample Call", keywords: "agent whitfield oracle jet 21-23g merged anchor", snippet: "Full transcript using the merged A+H → N → C → O → R flow." },
  { title: "Sample Call Score Card", page: "06-sample-call.html", anchor: "scorecard", pageTitle: "Sample Call", keywords: "post call rating high medium low", snippet: "Rated High/Medium on each ANCHOR step, with notes." },

  // 07 - Warranty & Goodwill
  { title: "Goodwill Policy", page: "07-warranty-goodwill.html", anchor: "goodwill-policy", pageTitle: "Warranty & Goodwill", keywords: "trust protection not entitlement when to consider what it can include", snippet: "Goodwill = Trust Protection, Not Entitlement. When to consider it, what it can include." },
  { title: "What to Avoid in Customer Care", page: "07-warranty-goodwill.html", anchor: "avoid", pageTitle: "Warranty & Goodwill", keywords: "guarantee only measure fairness promising before approval", snippet: "Behaviours to avoid - treating guarantee as only fairness measure, promising before approval." },
  { title: "Warranty/Repair by Product Category", page: "07-warranty-goodwill.html", anchor: "warranty-by-category", pageTitle: "Warranty & Goodwill", keywords: "non-coffee appliances grinders drip machines nespresso 30 percent discount", snippet: "Replace vs. discount rules by appliance category." },
  { title: "Sending Repair Templates", page: "07-warranty-goodwill.html", anchor: "repair-templates", pageTitle: "Warranty & Goodwill", keywords: "029A 029B windhorn dynafix axiomes grace period L03 box needed", snippet: "Which template to send by region, warranty status, and product." },
  { title: "Unrepairable Machines", page: "07-warranty-goodwill.html", anchor: "unrepairable", pageTitle: "Warranty & Goodwill", keywords: "repair replacement 900 series 60 percent 50 percent windhorn RM offer", snippet: "In-warranty and out-of-warranty rules when a machine can't be repaired." },
  { title: "Repeat Failure Cases", page: "07-warranty-goodwill.html", anchor: "repeat-failure", pageTitle: "Warranty & Goodwill", keywords: "repeat repair failure 24+12 months FOC error 5 under-heating loctite", snippet: "Replace vs. repair rules for repeat failures, in and out of warranty." },
  { title: "RM Units (Refurbished / Third-Party)", page: "07-warranty-goodwill.html", anchor: "rm-units", pageTitle: "Warranty & Goodwill", keywords: "idoodirect windhorn 12 months serial number RM retailer warranty", snippet: "Spotting RM units and where their warranty claims go." },

  // 08 - Salesforce Process
  { title: "Which Route Am I On?", page: "08-salesforce-process.html", anchor: "which-route", pageTitle: "Salesforce Process", keywords: "accommodation sale at 0 cost sales order machine spare part routing", snippet: "Two questions to determine Accommodation vs. Sale-at-0-cost vs. Sales order." },
  { title: "Groundwork - Account, Asset, Case", page: "08-salesforce-process.html", anchor: "groundwork", pageTitle: "Salesforce Process", keywords: "create account asset registered product case comments private vital signs stepper", snippet: "Full 6-step walkthrough: create account, create asset, create case, product info, description info, finish." },
  { title: "Step: Create the Account", page: "08-salesforce-process.html", anchor: "step-create-account", pageTitle: "Salesforce Process", keywords: "first name last name phone country code email language preference currency phonetic alphabet", snippet: "Every field needed to create a customer account, and why language/currency matter." },
  { title: "Step: Create the Asset (Registered Product)", page: "08-salesforce-process.html", anchor: "step-create-asset", pageTitle: "Salesforce Process", keywords: "asset name product model purchase date batch code 1111 serial number", snippet: "Fields for creating or updating a registered product." },
  { title: "Step: Create the Case - Case Details", page: "08-salesforce-process.html", anchor: "step-create-case", pageTitle: "Salesforce Process", keywords: "inquiry type status waiting reason case currency country language", snippet: "The first set of fields when opening a new case." },
  { title: "Step: Case Product Info", page: "08-salesforce-process.html", anchor: "step-case-product-info", pageTitle: "Salesforce Process", keywords: "product brand batch code serial purchase from order link asset", snippet: "Linking the case to the machine and where it was purchased." },
  { title: "Step: Case Description Information", page: "08-salesforce-process.html", anchor: "step-case-description-info", pageTitle: "Salesforce Process", keywords: "complaint code sub complaint subject description repair centre instructions", snippet: "What the repair centre reads as their instructions." },
  { title: "Step: Finish the Case (Vital Signs, Email, Comment)", page: "08-salesforce-process.html", anchor: "step-case-finish", pageTitle: "Salesforce Process", keywords: "vital signs send email case comment private never public", snippet: "The three-part close on every case, and the private-comment rule." },
  { title: "The Six Order Routes", page: "08-salesforce-process.html", anchor: "six-routes", pageTitle: "Salesforce Process", keywords: "accommodation machine spare parts sale 0 cost full price discount new order", snippet: "Step-by-step for all six order routes." },
  { title: "Patterns Worth Memorising", page: "08-salesforce-process.html", anchor: "patterns", pageTitle: "Salesforce Process", keywords: "new order shipping method activate send quote complimentary shipping return label", snippet: "The shortcuts that repeat across every route." },
  { title: "Case Notes Template", page: "08-salesforce-process.html", anchor: "case-notes", pageTitle: "Salesforce Process", keywords: "contact type reason discussed actions taken next steps", snippet: "Standard note-taking template for every contact." },
  { title: "Cancellations", page: "08-salesforce-process.html", anchor: "cancellations", pageTitle: "Salesforce Process", keywords: "task force misc queue shipped RMA order generated", snippet: "All cancellations go to Task Force unless the order already shipped." },
  { title: "Backorder & Stock", page: "08-salesforce-process.html", anchor: "backorder", pageTitle: "Salesforce Process", keywords: "notify me out of stock reserved BDE AE never tell stock amount", snippet: "Checking stock and handling backordered machines." },
  { title: "ScreenMeet", page: "08-salesforce-process.html", anchor: "screenmeet", pageTitle: "Salesforce Process", keywords: "invite link android ios chrome customer cannot see us", snippet: "Screen-sharing tool - use often; iOS only works in Chrome." },
  { title: "Automatic Refunds", page: "08-salesforce-process.html", anchor: "refund-automatic", pageTitle: "Salesforce Process", keywords: "refund button final return DIF 30 days return label", snippet: "Conditions and steps for the automatic Refund button." },
  { title: "Manual Refunds (escalation)", page: "08-salesforce-process.html", anchor: "refund-manual", pageTitle: "Salesforce Process", keywords: "escalate misc refund request EUR order number partial", snippet: "When RMA can't process automatically - escalate to Misc instead." },
  { title: "B2C RMA - Full Refund Case Build", page: "08-salesforce-process.html", anchor: "refund-b2c-rma", pageTitle: "Salesforce Process", keywords: "support and service final return buyer's remorse return location", snippet: "Building a complete refund case for a website-purchased machine." },
  { title: "The Refund Flow Screen", page: "08-salesforce-process.html", anchor: "refund-flow-screen", pageTitle: "Salesforce Process", keywords: "action column DIF destroy in field submit extended warranty", snippet: "How to use the Refund screen once you click Refund." },
  { title: "The Shipping Cost Trap", page: "08-salesforce-process.html", anchor: "refund-flow-screen", pageTitle: "Salesforce Process", keywords: "40 EUR shipping cost manual refund financial information", snippet: "Orders ≤40 EUR with shipping costs need a manual refund, not automatic." },
  { title: "VAT Invoice Requests", page: "08-salesforce-process.html", anchor: "vat", pageTitle: "Salesforce Process", keywords: "registration and promotion proof of purchase refund and billing queue BDE BCH BUK BAE", snippet: "Complaint code, escalation queue, and business unit codes for VAT requests." },
  { title: "SIA - Shipping In Advance", page: "08-salesforce-process.html", anchor: "sia", pageTitle: "Salesforce Process", keywords: "deposit authorised charged 20 days CC authorization amount", snippet: "Deposit rules: authorised not charged, voids in 20 days if returned." },
  { title: "Escalation to Tier 2", page: "08-salesforce-process.html", anchor: "escalation-tier2", pageTitle: "Salesforce Process", keywords: "feed comment unit model specifications POP previous case", snippet: "Two-part escalation - Escalate tab, then Feed comment template." },
  { title: "Non-Activated Orders", page: "08-salesforce-process.html", anchor: "non-activated", pageTitle: "Salesforce Process", keywords: "task force activation missing product SKU", snippet: "Task Force deletes orders missing a product; you handle activation." },
  { title: "Where the Buttons Are / Case Status Path", page: "08-salesforce-process.html", anchor: "ui-map", pageTitle: "Salesforce Process", keywords: "toolbar new order refund warranty approval waiting on consumer closed", snippet: "Toolbar layout and the case status bar from open to closed." },

  // 09 - Glossary / Team / Ops
  { title: "Team & Roles", page: "09-glossary-team-ops.html", anchor: "team", pageTitle: "Glossary, Team & Ops", keywords: "supervisor T2 T3 task force baratza beanz escalation chain", snippet: "Team structure - supervisors, T2/T3, Task Force, Baratza and Beanz teams." },
  { title: "Escalation Chain, in Order", page: "09-glossary-team-ops.html", anchor: "escalation-chain", pageTitle: "Glossary, Team & Ops", keywords: "front-line agent T2 task force goodwill reassure flowchart escalate", snippet: "Flowchart: front-line agent to T2 to Task Force to Goodwill to close." },
  { title: "Abbreviation Glossary", page: "09-glossary-team-ops.html", anchor: "glossary", pageTitle: "Glossary, Team & Ops", keywords: "ACCO ASC DOA FOC GWG IW OOW POP RM SF SKU TBS WO", snippet: "Full A-Z abbreviation list used in cases and comments." },
  { title: "Greek Bank Holidays (Pay Rule)", page: "09-glossary-team-ops.html", anchor: "holidays", pageTitle: "Glossary, Team & Ops", keywords: "75 percent sunday holiday pay epiphany independence day", snippet: "+75% pay for Sundays and the 9 official Greek bank holidays." },
  { title: "AUX / Status Codes", page: "09-glossary-team-ops.html", anchor: "aux", pageTitle: "Glossary, Team & Ops", keywords: "available phone case chat training meeting break busy extended ACW RTM", snippet: "Which AUX statuses are allowed and when." },

  // 10 - Cram Sheet
  { title: "Key Numbers Cheat Table", page: "10-cram-sheet.html", anchor: "key-numbers", pageTitle: "Cram Sheet", keywords: "all key numbers dose pressure temperature tamp refund window", snippet: "Every critical number in the knowledge base, in one table." },
  { title: "Golden Rules - Never / Always", page: "10-cram-sheet.html", anchor: "golden-rules", pageTitle: "Cram Sheet", keywords: "never always rules tamper fan latch public case comment full price", snippet: "The non-negotiable rules worth having memorized." },
  { title: "Gotchas & Flagged Contradictions", page: "10-cram-sheet.html", anchor: "gotchas", pageTitle: "Cram Sheet", keywords: "contradiction full price glossary unsettled dimensions weight", snippet: "Known inconsistencies in the source material to be aware of." },
  { title: "Self-Check Questions", page: "10-cram-sheet.html", anchor: "self-check", pageTitle: "Cram Sheet", keywords: "practice quiz questions test yourself", snippet: "Click-to-reveal practice questions across every topic." },

  // 11 - Descaling & Machine Cleaning
  { title: "Why It Matters", page: "00-descaling-cleaning.html", anchor: "why-it-matters", pageTitle: "Descaling & Machine Cleaning", keywords: "machine hygiene must common issues descale clean indicator", snippet: "Cleaning and descaling cadence is a MUST - most common issues trace back to skipping it." },
  { title: "Cleaning vs. Descaling", page: "00-descaling-cleaning.html", anchor: "cleaning-vs-descaling", pageTitle: "Descaling & Machine Cleaning", keywords: "cleaning cycle descale cycle oil buildup scale limescale water hardness descaling powder solution sachet", snippet: "What each cycle actually clears, and what triggers it." },
  { title: "General Care Rules (All Models)", page: "00-descaling-cleaning.html", anchor: "general-care", pageTitle: "Descaling & Machine Cleaning", keywords: "hand-wash dishwasher abrasive demineralised distilled water filter unroasted beans warranty void", snippet: "The non-negotiable care rules that apply to every machine, every time." },
  { title: "Step-by-Step, By Model", page: "00-descaling-cleaning.html", anchor: "by-model", pageTitle: "Descaling & Machine Cleaning", keywords: "bambino barista express impress pro touch dual boiler oracle jet cleaning cycle descale steps button combination", snippet: "Exact cleaning and descale steps for all 11 models, transcribed from source." },
  { title: "Talking the Customer Through It", page: "00-descaling-cleaning.html", anchor: "talking-to-customer", pageTitle: "Descaling & Machine Cleaning", keywords: "knowledgeable customer unsure customer instructions phrasing plain language explain descale clean", snippet: "How to walk a confident customer vs. an unsure one through the same cleaning or descale cycle." }
];
